# Generated by Django 4.1.7 on 2023-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_drinkcategory_drink_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('time_log', models.TimeField(help_text='Enter the exact time!')),
            ],
        ),
    ]
