# Generated by Django 4.1.7 on 2023-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_comments_booking_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
